-- Add Pi-Rating columns to TeamRating
ALTER TABLE "TeamRating" ADD COLUMN IF NOT EXISTS "piHa" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TeamRating" ADD COLUMN IF NOT EXISTS "piHd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TeamRating" ADD COLUMN IF NOT EXISTS "piAa" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TeamRating" ADD COLUMN IF NOT EXISTS "piAd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TeamRating" ADD COLUMN IF NOT EXISTS "piMatches" INTEGER NOT NULL DEFAULT 0;
