// ── Goaloo League Catalogue (166 leagues) ──────────────────────────
// Goaloo internal league IDs for season-JSON endpoint:
//   https://football.goaloo.com/jsData/matchResult/json/{season}/s{id}_en.json
//
// Source: football.goaloo.com league catalogue, verified Jun 2026.
// These are the leagues used by /admin/ml/data-import → Goaloo source.

export interface GoalooLeague {
  id: number;
  shortName: string;
  fullName: string;
}

export const GOALOO_LEAGUES: GoalooLeague[] = [
  { id: 1, shortName: "IRE PR", fullName: "Ireland Premier Division" },
  { id: 2, shortName: "ARG D1", fullName: "Argentine Division 1" },
  { id: 3, shortName: "AUT D1", fullName: "Austrian Bundesliga" },
  { id: 4, shortName: "BRA D1", fullName: "Brazil Serie A" },
  { id: 5, shortName: "BEL D1", fullName: "Belgian Pro League" },
  { id: 6, shortName: "POL PR", fullName: "Poland Ekstraklasa" },
  { id: 7, shortName: "DEN SASL", fullName: "Denmark Superliga" },
  { id: 8, shortName: "GER D1", fullName: "German Bundesliga" },
  { id: 9, shortName: "GER D2", fullName: "German Bundesliga 2" },
  { id: 10, shortName: "RUS PR", fullName: "Russia Premier League" },
  { id: 11, shortName: "FRA D1", fullName: "France Ligue 1" },
  { id: 12, shortName: "FRA D2", fullName: "France Ligue 2" },
  { id: 13, shortName: "FIN D1", fullName: "Finland Veikkausliga" },
  { id: 15, shortName: "KOR D1", fullName: "K League 1" },
  { id: 16, shortName: "HOL D1", fullName: "Holland Eredivisie" },
  { id: 17, shortName: "HOL D2", fullName: "Holland Eerste Divisie" },
  { id: 21, shortName: "MLS", fullName: "USA Major League Soccer" },
  { id: 22, shortName: "NOR D1", fullName: "Norway Eliteserien" },
  { id: 23, shortName: "POR D1", fullName: "Liga Portugal 1" },
  { id: 25, shortName: "JPN D1", fullName: "Japan J1 League" },
  { id: 26, shortName: "SWE D1", fullName: "Swedish Allsvenskan" },
  { id: 27, shortName: "SUI SL", fullName: "Switzerland Super League" },
  { id: 29, shortName: "SCO PR", fullName: "Scottish Premiership" },
  { id: 30, shortName: "TUR D1", fullName: "Turkey Super Lig" },
  { id: 31, shortName: "SPA D1", fullName: "Spanish La Liga" },
  { id: 32, shortName: "GRE D1", fullName: "Greece Super League A" },
  { id: 33, shortName: "SPA D2", fullName: "Spanish La Liga 2" },
  { id: 34, shortName: "ITA D1", fullName: "Italy Serie A" },
  { id: 35, shortName: "ENG L2", fullName: "England League 2" },
  { id: 36, shortName: "ENG PR", fullName: "English Premier League" },
  { id: 37, shortName: "ENG LCH", fullName: "England Championship" },
  { id: 39, shortName: "ENG L1", fullName: "England League 1" },
  { id: 40, shortName: "ITA D2", fullName: "Italy Serie B" },
  { id: 60, shortName: "CHA CSL", fullName: "Chinese Super League" },
  { id: 61, shortName: "CHA D1", fullName: "Chinese Football Association Jia League" },
  { id: 118, shortName: "ISR D1", fullName: "Israel Premier League" },
  { id: 119, shortName: "UKR D1", fullName: "Ukrainian Premier League" },
  { id: 120, shortName: "SLO D2", fullName: "Slovenia 2.Liga" },
  { id: 121, shortName: "SUI CL", fullName: "Switzerland Challenge League" },
  { id: 122, shortName: "SWE D2", fullName: "Sweden Superettan" },
  { id: 123, shortName: "NOR AL", fullName: "Norway Adeccoligaen" },
  { id: 124, shortName: "ROM D1", fullName: "Romania Liga I" },
  { id: 127, shortName: "DEN D1", fullName: "Danish 1st Division" },
  { id: 128, shortName: "AUT D2", fullName: "Austria Erste Division" },
  { id: 129, shortName: "SER D1", fullName: "Serbian Superliga" },
  { id: 130, shortName: "TFF 1. Lig", fullName: "Turkey 1. Lig" },
  { id: 131, shortName: "BUL FL", fullName: "Bulgaria First League" },
  { id: 132, shortName: "SVK D1", fullName: "Slovak Super Liga" },
  { id: 133, shortName: "CRO D1", fullName: "Croatia 1.Division" },
  { id: 135, shortName: "Welsh PR", fullName: "Welsh Premier League" },
  { id: 136, shortName: "HUN D1", fullName: "Hungary Borsodi Liga" },
  { id: 137, shortName: "CZE D1", fullName: "Czech Republic Gambrinus Liga" },
  { id: 138, shortName: "BEL D2", fullName: "Belgian Second Division" },
  { id: 139, shortName: "IRE D1", fullName: "Ireland First Division" },
  { id: 140, shortName: "MEX D1", fullName: "Primera Division Liga MX" },
  { id: 157, shortName: "POR D2", fullName: "Liga Portugal 2" },
  { id: 159, shortName: "CYP D1", fullName: "Cyprus 1 Division" },
  { id: 160, shortName: "ISR D2", fullName: "Israel Leumit League" },
  { id: 165, shortName: "NIR D1", fullName: "Northern Ireland Premier League" },
  { id: 166, shortName: "ICE PR", fullName: "Iceland Premier Division" },
  { id: 170, shortName: "GRE D2", fullName: "Greece National B" },
  { id: 193, shortName: "ALG D1", fullName: "Algerian Ligue Professionnelle 1" },
  { id: 194, shortName: "SIN D1", fullName: "Singapore League" },
  { id: 203, shortName: "FRA D3", fullName: "Championnat National" },
  { id: 212, shortName: "FIN D2", fullName: "Finland Ykkonen" },
  { id: 214, shortName: "LAT D1", fullName: "Latvian Higher League" },
  { id: 221, shortName: "POL D1", fullName: "Poland Liga 1" },
  { id: 230, shortName: "BLR D1", fullName: "Belarusian Premier League" },
  { id: 235, shortName: "RUS D1", fullName: "Russian National Football League" },
  { id: 240, shortName: "URU D1", fullName: "Liga AUF Uruguaya" },
  { id: 242, shortName: "PER L1", fullName: "Peru Liga 1" },
  { id: 247, shortName: "SLO D1", fullName: "Slovenia 1.Liga" },
  { id: 250, shortName: "COL D1", fullName: "Categoria Primera A" },
  { id: 273, shortName: "AUS D1", fullName: "Australia A-League" },
  { id: 279, shortName: "IRN PR", fullName: "Persian Gulf Pro League" },
  { id: 284, shortName: "JPN D2", fullName: "J2 League" },
  { id: 290, shortName: "CZE D2", fullName: "Czech Republic 2.Liga" },
  { id: 292, shortName: "SPL", fullName: "Saudi Professional League" },
  { id: 301, shortName: "UAE LP", fullName: "UAE Pro-League" },
  { id: 303, shortName: "EGY D1", fullName: "Egyptian Premier League" },
  { id: 308, shortName: "SAPL D1", fullName: "South Africa Premier Soccer League" },
  { id: 309, shortName: "JOR D1", fullName: "Jordan Premier League" },
  { id: 311, shortName: "HK PR", fullName: "Hong Kong Premier League" },
  { id: 313, shortName: "QAT D1", fullName: "Qatar Stars League" },
  { id: 315, shortName: "ALB D1", fullName: "Albania Super league" },
  { id: 316, shortName: "MAS SL", fullName: "Liga Super Malaysia" },
  { id: 317, shortName: "MAS PL", fullName: "Malaysia Premier League" },
  { id: 318, shortName: "BHR D1", fullName: "Bahraini Premier League" },
  { id: 321, shortName: "MAR D1", fullName: "Botola Pro 1" },
  { id: 322, shortName: "KUW D1", fullName: "Kuwaiti Premier League" },
  { id: 324, shortName: "LIBD1L", fullName: "Libyan Premier League" },
  { id: 325, shortName: "LBN D1", fullName: "Lebanese Premier League" },
  { id: 326, shortName: "TUN D1", fullName: "Professional Tunisian League 1" },
  { id: 332, shortName: "OMA PL", fullName: "Oman Professional League" },
  { id: 341, shortName: "NZNL", fullName: "New Zealand National League" },
  { id: 348, shortName: "ALB D2", fullName: "Albania Kategoria e Pare" },
  { id: 349, shortName: "SVK D2", fullName: "Slovakia 2. Liga" },
  { id: 350, shortName: "BOS PL", fullName: "Bosnia and Herzegovina Premier League" },
  { id: 351, shortName: "EST D1", fullName: "Estonia Champions League" },
  { id: 352, shortName: "PAR D1", fullName: "Primera Division de Paraguay" },
  { id: 354, shortName: "BRA D2", fullName: "Brazil Serie B" },
  { id: 381, shortName: "ICE D1", fullName: "Iceland Division 1" },
  { id: 389, shortName: "MOL D1", fullName: "Moldova Divizia Nationala" },
  { id: 391, shortName: "VEN D1", fullName: "Primera Division de Venezuela" },
  { id: 392, shortName: "MKD D1", fullName: "Macedonian First Football League" },
  { id: 415, shortName: "CHI D1", fullName: "Chile Primera Division" },
  { id: 423, shortName: "ARG D2", fullName: "Argentine Division 2" },
  { id: 448, shortName: "USL CH", fullName: "USL Championship" },
  { id: 456, shortName: "KOR D3", fullName: "Korea National League" },
  { id: 460, shortName: "CAN CSL", fullName: "Canadian Premier Soccer League" },
  { id: 466, shortName: "KAZ PR", fullName: "Kazakhstan Premier League" },
  { id: 469, shortName: "ARM D1", fullName: "Armenia Premier League" },
  { id: 465, shortName: "YEM D1", fullName: "Yemeni League" },
  { id: 481, shortName: "WAUS D1", fullName: "National Premier Leagues Western Australia" },
  { id: 504, shortName: "CRC D1", fullName: "Costa Rica Primera Division" },
  { id: 511, shortName: "SLV D1", fullName: "Primera Division de El Salvador" },
  { id: 514, shortName: "LUX D1", fullName: "Luxembourg National Division" },
  { id: 533, shortName: "MAL D1", fullName: "Malta Premier League" },
  { id: 562, shortName: "MNE D1", fullName: "Montenegro Prva Crnogorska Liga" },
  { id: 563, shortName: "GEO D1", fullName: "Georgia Primera Division" },
  { id: 576, shortName: "FAR D1", fullName: "Faroe Islands Formuladeildin" },
  { id: 577, shortName: "HON Lig1", fullName: "Liga Nacional de Honduras" },
  { id: 579, shortName: "GUA D1", fullName: "Liga Nacional de Guatemala" },
  { id: 593, shortName: "BOL D1", fullName: "Bolivia Primera Division" },
  { id: 596, shortName: "ECU LPSA", fullName: "Liga Pro Ecuador Serie A" },
  { id: 604, shortName: "HOL BD1", fullName: "Holland Beloften Eredivisie" },
  { id: 611, shortName: "CHI D2", fullName: "Chile Primera B" },
  { id: 613, shortName: "AZE D1", fullName: "Azerbaijan Premier League" },
  { id: 616, shortName: "AUS NSW", fullName: "NSW Premier League" },
  { id: 630, shortName: "KCL", fullName: "Korea Challengers League" },
  { id: 686, shortName: "CHA D2", fullName: "Chinese Football Association Yi League" },
  { id: 693, shortName: "GER D3", fullName: "German 3.Liga" },
  { id: 700, shortName: "THA PR", fullName: "Thai League 1" },
  { id: 703, shortName: "HUN D2E", fullName: "Hungary NB II" },
  { id: 706, shortName: "CZE CFL", fullName: "Czech Republic Ceska Fotbalova Liga" },
  { id: 722, shortName: "AUS YL", fullName: "A-League National Youth League" },
  { id: 740, shortName: "UAE D1", fullName: "UAE Division 1 Group A" },
  { id: 745, shortName: "KSA D1", fullName: "Saudi Arabia Division 1" },
  { id: 748, shortName: "NIR CH", fullName: "Northern Ireland IFA Championship" },
  { id: 763, shortName: "IND D1", fullName: "India League Division 1" },
  { id: 766, shortName: "VIE D1", fullName: "V.League 1" },
  { id: 772, shortName: "UZB D1", fullName: "Uzbek League" },
  { id: 780, shortName: "JPN JFL", fullName: "Japan Football League" },
  { id: 847, shortName: "MEX Lig2", fullName: "Liga de Expansion MX" },
  { id: 863, shortName: "ALG D2", fullName: "Algerian Ligue Professionnelle 2" },
  { id: 872, shortName: "UKR D2", fullName: "Ukraine Division 2" },
  { id: 880, shortName: "ANDPD", fullName: "Andorra Primera Divisió" },
  { id: 890, shortName: "IRN D1", fullName: "Azadegan League" },
  { id: 893, shortName: "HUN U19A", fullName: "Hungary U19 A League" },
  { id: 896, shortName: "BHR D", fullName: "Bahrain Division" },
  { id: 897, shortName: "LIT D2", fullName: "Lithuania - 2.Division" },
  { id: 907, shortName: "SAFL", fullName: "South Africa First League" },
  { id: 915, shortName: "CYP D2", fullName: "Cyprus 2 Division" },
  { id: 917, shortName: "ARG B M", fullName: "Argentina Primera B Metropolitana" },
  { id: 923, shortName: "KUW D2", fullName: "Kuwait Division 1" },
  { id: 949, shortName: "NGA PR", fullName: "Nigerian Premier League" },
  { id: 950, shortName: "KSA D2", fullName: "Saudi Arabia Division 2" },
  { id: 953, shortName: "MAR D2", fullName: "Botola 2" },
  { id: 976, shortName: "YEM D2", fullName: "Yemen League Division 2" },
  { id: 1000, shortName: "MAL D2", fullName: "Malta First Division League" },
  { id: 1014, shortName: "MOL D2", fullName: "Moldova Division 2" },
  { id: 1029, shortName: "AUS SASL", fullName: "FFSA Premier League" },
  { id: 1043, shortName: "EST D2", fullName: "Estonia Esi Liiga" },
  { id: 1046, shortName: "BLR D2", fullName: "Belarus Pershaya Liga" },
  { id: 1048, shortName: "THA L2", fullName: "Thai League 2" },
  { id: 1054, shortName: "IRQ SL", fullName: "Iraq Stars League" },
];
